// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Dart bindings for Nexus Storage core engine (Rust).
class NexusCoreBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NexusCoreBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NexusCoreBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Free a byte buffer previously allocated by the nexus-core library.
  void nexus_free_bytes(ffi.Pointer<ffi.Uint8> ptr, int len) {
    return _nexus_free_bytes(ptr, len);
  }

  late final _nexus_free_bytesPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.Size)>
      >('nexus_free_bytes');
  late final _nexus_free_bytes = _nexus_free_bytesPtr
      .asFunction<void Function(ffi.Pointer<ffi.Uint8>, int)>();

  /// Encrypt bytes with a password.
  /// out_ptr will point to a buffer that must be freed with nexus_free_bytes.
  int nexus_encrypt(
    ffi.Pointer<ffi.Uint8> in_ptr,
    int in_len,
    ffi.Pointer<ffi.Char> password,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
    ffi.Pointer<ffi.Size> out_len,
  ) {
    return _nexus_encrypt(in_ptr, in_len, password, out_ptr, out_len);
  }

  late final _nexus_encryptPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('nexus_encrypt');
  late final _nexus_encrypt = _nexus_encryptPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  /// Decrypt bytes with a password.
  /// out_ptr will point to a buffer that must be freed with nexus_free_bytes.
  int nexus_decrypt(
    ffi.Pointer<ffi.Uint8> in_ptr,
    int in_len,
    ffi.Pointer<ffi.Char> password,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
    ffi.Pointer<ffi.Size> out_len,
  ) {
    return _nexus_decrypt(in_ptr, in_len, password, out_ptr, out_len);
  }

  late final _nexus_decryptPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('nexus_decrypt');
  late final _nexus_decrypt = _nexus_decryptPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  /// Compress bytes.
  /// level: 0=auto, 1=lz4, 2=zstd, 3=lzma, 4=store
  /// out_ptr will point to a buffer that must be freed with nexus_free_bytes.
  int nexus_compress(
    ffi.Pointer<ffi.Uint8> in_ptr,
    int in_len,
    int level,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
    ffi.Pointer<ffi.Size> out_len,
  ) {
    return _nexus_compress(in_ptr, in_len, level, out_ptr, out_len);
  }

  late final _nexus_compressPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Int32,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('nexus_compress');
  late final _nexus_compress = _nexus_compressPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Uint8>,
          int,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  /// Decompress bytes.
  /// out_ptr will point to a buffer that must be freed with nexus_free_bytes.
  int nexus_decompress(
    ffi.Pointer<ffi.Uint8> in_ptr,
    int in_len,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
    ffi.Pointer<ffi.Size> out_len,
  ) {
    return _nexus_decompress(in_ptr, in_len, out_ptr, out_len);
  }

  late final _nexus_decompressPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('nexus_decompress');
  late final _nexus_decompress = _nexus_decompressPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  /// Compute SHA-256 hex fingerprint.
  /// out_hex must be at least 65 bytes long.
  int nexus_sha256_hex(
    ffi.Pointer<ffi.Uint8> in_ptr,
    int in_len,
    ffi.Pointer<ffi.Char> out_hex,
  ) {
    return _nexus_sha256_hex(in_ptr, in_len, out_hex);
  }

  late final _nexus_sha256_hexPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('nexus_sha256_hex');
  late final _nexus_sha256_hex = _nexus_sha256_hexPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Uint8>, int, ffi.Pointer<ffi.Char>)
      >();

  /// Encode bytes into PNG frames in output_dir.
  /// mode: 0=Tank, 1=Density
  /// Returns the number of frames written (positive) or a negative error code.
  int nexus_encode_to_frames(
    ffi.Pointer<ffi.Uint8> in_ptr,
    int in_len,
    ffi.Pointer<ffi.Char> output_dir,
    int mode,
  ) {
    return _nexus_encode_to_frames(in_ptr, in_len, output_dir, mode);
  }

  late final _nexus_encode_to_framesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Pointer<ffi.Char>,
            ffi.Int32,
          )
        >
      >('nexus_encode_to_frames');
  late final _nexus_encode_to_frames = _nexus_encode_to_framesPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Uint8>, int, ffi.Pointer<ffi.Char>, int)
      >();

  /// Decode a payload from PNG frames in frame_dir.
  /// mode: 0=Tank, 1=Density
  /// out_ptr will point to a buffer that must be freed with nexus_free_bytes.
  /// Returns 0 on success or a negative error code.
  int nexus_decode_from_frames(
    ffi.Pointer<ffi.Char> frame_dir,
    int mode,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
    ffi.Pointer<ffi.Size> out_len,
  ) {
    return _nexus_decode_from_frames(frame_dir, mode, out_ptr, out_len);
  }

  late final _nexus_decode_from_framesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int32,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('nexus_decode_from_frames');
  late final _nexus_decode_from_frames = _nexus_decode_from_framesPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  /// Generate a cryptographically random 32-byte file key.
  /// out_ptr will point to a buffer that must be freed with nexus_free_bytes.
  int nexus_generate_file_key(
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
    ffi.Pointer<ffi.Size> out_len,
  ) {
    return _nexus_generate_file_key(out_ptr, out_len);
  }

  late final _nexus_generate_file_keyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('nexus_generate_file_key');
  late final _nexus_generate_file_key = _nexus_generate_file_keyPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Pointer<ffi.Uint8>>, ffi.Pointer<ffi.Size>)
      >();

  /// Encrypt bytes using a raw 32-byte file key (bypasses PBKDF2).
  /// key_ptr must point to exactly 32 bytes.
  /// out_ptr will point to a buffer that must be freed with nexus_free_bytes.
  int nexus_encrypt_with_key(
    ffi.Pointer<ffi.Uint8> in_ptr,
    int in_len,
    ffi.Pointer<ffi.Uint8> key_ptr,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
    ffi.Pointer<ffi.Size> out_len,
  ) {
    return _nexus_encrypt_with_key(in_ptr, in_len, key_ptr, out_ptr, out_len);
  }

  late final _nexus_encrypt_with_keyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Pointer<ffi.Uint8>,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('nexus_encrypt_with_key');
  late final _nexus_encrypt_with_key = _nexus_encrypt_with_keyPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Uint8>,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  /// Decrypt a blob produced by nexus_encrypt_with_key.
  /// key_ptr must point to exactly 32 bytes.
  /// out_ptr will point to a buffer that must be freed with nexus_free_bytes.
  int nexus_decrypt_with_key(
    ffi.Pointer<ffi.Uint8> in_ptr,
    int in_len,
    ffi.Pointer<ffi.Uint8> key_ptr,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
    ffi.Pointer<ffi.Size> out_len,
  ) {
    return _nexus_decrypt_with_key(in_ptr, in_len, key_ptr, out_ptr, out_len);
  }

  late final _nexus_decrypt_with_keyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Pointer<ffi.Uint8>,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('nexus_decrypt_with_key');
  late final _nexus_decrypt_with_key = _nexus_decrypt_with_keyPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Uint8>,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  /// (V4 Security) Generate a cryptographically random 16-byte recovery salt for Argon2.
  /// out_ptr will point to a buffer that must be freed with nexus_free_bytes.
  int nexus_generate_recovery_salt(
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
    ffi.Pointer<ffi.Size> out_len,
  ) {
    return _nexus_generate_recovery_salt(out_ptr, out_len);
  }

  late final _nexus_generate_recovery_saltPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('nexus_generate_recovery_salt');
  late final _nexus_generate_recovery_salt = _nexus_generate_recovery_saltPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Pointer<ffi.Uint8>>, ffi.Pointer<ffi.Size>)
      >();

  /// (V4 Security) Derive a 32-byte master key using Argon2id.
  /// password_ptr: null-terminated C string
  /// password_len: byte length (for validation)
  /// salt_ptr: must point to exactly 16 bytes
  /// salt_len: must be 16
  /// out_ptr will point to a buffer that must be freed with nexus_free_bytes.
  /// Returns 0 on success, negative error code otherwise.
  int nexus_derive_master_key(
    ffi.Pointer<ffi.Char> password_ptr,
    int password_len,
    ffi.Pointer<ffi.Uint8> salt_ptr,
    int salt_len,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
    ffi.Pointer<ffi.Size> out_len,
  ) {
    return _nexus_derive_master_key(
      password_ptr,
      password_len,
      salt_ptr,
      salt_len,
      out_ptr,
      out_len,
    );
  }

  late final _nexus_derive_master_keyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Char>,
            ffi.Size,
            ffi.Pointer<ffi.Uint8>,
            ffi.Size,
            ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
            ffi.Pointer<ffi.Size>,
          )
        >
      >('nexus_derive_master_key');
  late final _nexus_derive_master_key = _nexus_derive_master_keyPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  /// --- Streaming API (Hardened) ---

  /// Initialize an encryption stream context.
  ffi.Pointer<StreamingContext> nexus_encrypt_stream_init(
    ffi.Pointer<ffi.Uint8> key_ptr,
    ffi.Pointer<ffi.Uint8> out_nonce_prefix,
  ) {
    return _nexus_encrypt_stream_init(key_ptr, out_nonce_prefix);
  }

  late final _nexus_encrypt_stream_initPtr = _lookup<
    ffi.NativeFunction<
      ffi.Pointer<StreamingContext> Function(
        ffi.Pointer<ffi.Uint8>,
        ffi.Pointer<ffi.Uint8>,
      )
    >
  >('nexus_encrypt_stream_init');
  late final _nexus_encrypt_stream_init = _nexus_encrypt_stream_initPtr
      .asFunction<
        ffi.Pointer<StreamingContext> Function(
          ffi.Pointer<ffi.Uint8>,
          ffi.Pointer<ffi.Uint8>,
        )
      >();

  ffi.Pointer<StreamingContext> nexus_decrypt_stream_init(
    ffi.Pointer<ffi.Uint8> key_ptr,
    ffi.Pointer<ffi.Uint8> nonce_prefix_ptr,
  ) {
    return _nexus_decrypt_stream_init(key_ptr, nonce_prefix_ptr);
  }

  late final _nexus_decrypt_stream_initPtr = _lookup<
    ffi.NativeFunction<
      ffi.Pointer<StreamingContext> Function(
        ffi.Pointer<ffi.Uint8>,
        ffi.Pointer<ffi.Uint8>,
      )
    >
  >('nexus_decrypt_stream_init');
  late final _nexus_decrypt_stream_init = _nexus_decrypt_stream_initPtr
      .asFunction<
        ffi.Pointer<StreamingContext> Function(
          ffi.Pointer<ffi.Uint8>,
          ffi.Pointer<ffi.Uint8>,
        )
      >();

  int nexus_encrypt_stream_update(
    ffi.Pointer<StreamingContext> ctx_ptr,
    ffi.Pointer<ffi.Uint8> in_ptr,
    int in_len,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
    ffi.Pointer<ffi.Size> out_len,
  ) {
    return _nexus_encrypt_stream_update(
      ctx_ptr,
      in_ptr,
      in_len,
      out_ptr,
      out_len,
    );
  }

  late final _nexus_encrypt_stream_updatePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<StreamingContext>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Size,
        ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
        ffi.Pointer<ffi.Size>,
      )
    >
  >('nexus_encrypt_stream_update');
  late final _nexus_encrypt_stream_update = _nexus_encrypt_stream_updatePtr
      .asFunction<
        int Function(
          ffi.Pointer<StreamingContext>,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  int nexus_decrypt_stream_update(
    ffi.Pointer<StreamingContext> ctx_ptr,
    ffi.Pointer<ffi.Uint8> in_ptr,
    int in_len,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
    ffi.Pointer<ffi.Size> out_len,
  ) {
    return _nexus_decrypt_stream_update(
      ctx_ptr,
      in_ptr,
      in_len,
      out_ptr,
      out_len,
    );
  }

  late final _nexus_decrypt_stream_updatePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<StreamingContext>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Size,
        ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
        ffi.Pointer<ffi.Size>,
      )
    >
  >('nexus_decrypt_stream_update');
  late final _nexus_decrypt_stream_update = _nexus_decrypt_stream_updatePtr
      .asFunction<
        int Function(
          ffi.Pointer<StreamingContext>,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  int nexus_encrypt_stream_finalize(
    ffi.Pointer<StreamingContext> ctx_ptr,
    ffi.Pointer<ffi.Uint8> in_ptr,
    int in_len,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
    ffi.Pointer<ffi.Size> out_len,
  ) {
    return _nexus_encrypt_stream_finalize(
      ctx_ptr,
      in_ptr,
      in_len,
      out_ptr,
      out_len,
    );
  }

  late final _nexus_encrypt_stream_finalizePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<StreamingContext>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Size,
        ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
        ffi.Pointer<ffi.Size>,
      )
    >
  >('nexus_encrypt_stream_finalize');
  late final _nexus_encrypt_stream_finalize = _nexus_encrypt_stream_finalizePtr
      .asFunction<
        int Function(
          ffi.Pointer<StreamingContext>,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  int nexus_decrypt_stream_finalize(
    ffi.Pointer<StreamingContext> ctx_ptr,
    ffi.Pointer<ffi.Uint8> in_ptr,
    int in_len,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
    ffi.Pointer<ffi.Size> out_len,
  ) {
    return _nexus_decrypt_stream_finalize(
      ctx_ptr,
      in_ptr,
      in_len,
      out_ptr,
      out_len,
    );
  }

  late final _nexus_decrypt_stream_finalizePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<StreamingContext>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Size,
        ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
        ffi.Pointer<ffi.Size>,
      )
    >
  >('nexus_decrypt_stream_finalize');
  late final _nexus_decrypt_stream_finalize = _nexus_decrypt_stream_finalizePtr
      .asFunction<
        int Function(
          ffi.Pointer<StreamingContext>,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  void nexus_crypto_stream_drop(ffi.Pointer<StreamingContext> ctx_ptr) {
    return _nexus_crypto_stream_drop(ctx_ptr);
  }

  late final _nexus_crypto_stream_dropPtr = _lookup<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<StreamingContext>)>
  >('nexus_crypto_stream_drop');
  late final _nexus_crypto_stream_drop = _nexus_crypto_stream_dropPtr
      .asFunction<void Function(ffi.Pointer<StreamingContext>)>();

  /// --- Encoder Streaming FFI ---

  ffi.Pointer<StreamingEncoder> nexus_encode_stream_init(int mode) {
    return _nexus_encode_stream_init(mode);
  }

  late final _nexus_encode_stream_initPtr = _lookup<
    ffi.NativeFunction<ffi.Pointer<StreamingEncoder> Function(ffi.Int32)>
  >('nexus_encode_stream_init');
  late final _nexus_encode_stream_init = _nexus_encode_stream_initPtr
      .asFunction<ffi.Pointer<StreamingEncoder> Function(int)>();

  int nexus_encode_stream_push(
    ffi.Pointer<StreamingEncoder> ctx_ptr,
    ffi.Pointer<ffi.Uint8> in_ptr,
    int in_len,
  ) {
    return _nexus_encode_stream_push(ctx_ptr, in_ptr, in_len);
  }

  late final _nexus_encode_stream_pushPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<StreamingEncoder>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Size,
      )
    >
  >('nexus_encode_stream_push');
  late final _nexus_encode_stream_push = _nexus_encode_stream_pushPtr
      .asFunction<int Function(ffi.Pointer<StreamingEncoder>, ffi.Pointer<ffi.Uint8>, int)>();

  int nexus_encode_stream_pop_frame(
    ffi.Pointer<StreamingEncoder> ctx_ptr,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
    ffi.Pointer<ffi.Size> out_len,
  ) {
    return _nexus_encode_stream_pop_frame(ctx_ptr, out_ptr, out_len);
  }

  late final _nexus_encode_stream_pop_framePtr = _lookup<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<StreamingEncoder>,
        ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
        ffi.Pointer<ffi.Size>,
      )
    >
  >('nexus_encode_stream_pop_frame');
  late final _nexus_encode_stream_pop_frame = _nexus_encode_stream_pop_framePtr
      .asFunction<
        int Function(
          ffi.Pointer<StreamingEncoder>,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  int nexus_encode_stream_finalize(ffi.Pointer<StreamingEncoder> ctx_ptr) {
    return _nexus_encode_stream_finalize(ctx_ptr);
  }

  late final _nexus_encode_stream_finalizePtr = _lookup<
    ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<StreamingEncoder>)>
  >('nexus_encode_stream_finalize');
  late final _nexus_encode_stream_finalize = _nexus_encode_stream_finalizePtr
      .asFunction<int Function(ffi.Pointer<StreamingEncoder>)>();

  void nexus_encoder_stream_drop(ffi.Pointer<StreamingEncoder> ctx_ptr) {
    return _nexus_encoder_stream_drop(ctx_ptr);
  }

  late final _nexus_encoder_stream_dropPtr = _lookup<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<StreamingEncoder>)>
  >('nexus_encoder_stream_drop');
  late final _nexus_encoder_stream_drop = _nexus_encoder_stream_dropPtr
      .asFunction<void Function(ffi.Pointer<StreamingEncoder>)>();

  /// --- Decoder Streaming FFI ---

  ffi.Pointer<StreamingDecoder> nexus_decode_stream_init(int mode) {
    return _nexus_decode_stream_init(mode);
  }

  late final _nexus_decode_stream_initPtr = _lookup<
    ffi.NativeFunction<ffi.Pointer<StreamingDecoder> Function(ffi.Int32)>
  >('nexus_decode_stream_init');
  late final _nexus_decode_stream_init = _nexus_decode_stream_initPtr
      .asFunction<ffi.Pointer<StreamingDecoder> Function(int)>();

  int nexus_decode_stream_push(
    ffi.Pointer<StreamingDecoder> ctx_ptr,
    ffi.Pointer<ffi.Uint8> in_ptr,
    int in_len,
  ) {
    return _nexus_decode_stream_push(ctx_ptr, in_ptr, in_len);
  }

  late final _nexus_decode_stream_pushPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<StreamingDecoder>,
        ffi.Pointer<ffi.Uint8>,
        ffi.Size,
      )
    >
  >('nexus_decode_stream_push');
  late final _nexus_decode_stream_push = _nexus_decode_stream_pushPtr
      .asFunction<int Function(ffi.Pointer<StreamingDecoder>, ffi.Pointer<ffi.Uint8>, int)>();

  int nexus_decode_stream_pop(
    ffi.Pointer<StreamingDecoder> ctx_ptr,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_ptr,
    ffi.Pointer<ffi.Size> out_len,
  ) {
    return _nexus_decode_stream_pop(ctx_ptr, out_ptr, out_len);
  }

  late final _nexus_decode_stream_popPtr = _lookup<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<StreamingDecoder>,
        ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
        ffi.Pointer<ffi.Size>,
      )
    >
  >('nexus_decode_stream_pop');
  late final _nexus_decode_stream_pop = _nexus_decode_stream_popPtr
      .asFunction<
        int Function(
          ffi.Pointer<StreamingDecoder>,
          ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
          ffi.Pointer<ffi.Size>,
        )
      >();

  void nexus_decoder_stream_drop(ffi.Pointer<StreamingDecoder> ctx_ptr) {
    return _nexus_decoder_stream_drop(ctx_ptr);
  }

  late final _nexus_decoder_stream_dropPtr = _lookup<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<StreamingDecoder>)>
  >('nexus_decoder_stream_drop');
  late final _nexus_decoder_stream_drop = _nexus_decoder_stream_dropPtr
      .asFunction<void Function(ffi.Pointer<StreamingDecoder>)>();
}

final class StreamingContext extends ffi.Opaque {}

final class StreamingEncoder extends ffi.Opaque {}

final class StreamingDecoder extends ffi.Opaque {}

const int NEXUS_OK = 0;

const int NEXUS_ERR_NULL_PTR = -1;

const int NEXUS_ERR_CRYPTO = -2;

const int NEXUS_ERR_COMPRESS = -3;

const int NEXUS_ERR_ENCODE = -4;

const int NEXUS_ERR_DECODE = -5;

const int NEXUS_ERR_IO = -6;
