package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"time"

	"google.golang.org/api/youtube/v3"
	"io"
)

type PlaylistManager struct {
	yt   *YouTubeManager
	db   *Database
	core *NexusCore
}

func NewPlaylistManager(yt *YouTubeManager, db *Database, core *NexusCore) *PlaylistManager {
	return &PlaylistManager{yt: yt, db: db, core: core}
}

// EnsureBasePlaylists creates NEXUS_ROOT and NEXUS_MANIFEST if they don't exist.
func (pm *PlaylistManager) EnsureBasePlaylists() error {
	svc := pm.yt.GetService()
	if svc == nil {
		return fmt.Errorf("YouTube service not available")
	}

	call := svc.Playlists.List([]string{"snippet", "id"}).Mine(true).MaxResults(50)
	resp, err := call.Do()
	if err != nil {
		return err
	}
	pm.db.LogQuotaUsage(1)

	foundRoot := ""
	foundManifest := ""

	for _, p := range resp.Items {
		switch p.Snippet.Title {
		case "NEXUS_ROOT":
			foundRoot = p.Id
		case "NEXUS_MANIFEST":
			foundManifest = p.Id
		}
	}

	if foundRoot == "" {
		title := "NEXUS_ROOT"
		desc := "Nexus-Storage Root Shards"
		if pm.db.IsStealthMode() {
			title = "DATA_ROOT_01"
			desc = "Autogenerated data collection."
		}
		p, err := pm.CreatePlaylist(title, desc)
		if err != nil {
			return err
		}
		foundRoot = p.Id
	}
	if foundManifest == "" {
		title := "NEXUS_MANIFEST"
		desc := "Nexus-Storage Database Backups"
		if pm.db.IsStealthMode() {
			title = "DATA_STATE_01"
			desc = "Autogenerated state collection."
		}
		p, err := pm.CreatePlaylist(title, desc)
		if err != nil {
			return err
		}
		foundManifest = p.Id
	}

	pm.db.SetKV("playlist_root_id", foundRoot)
	pm.db.SetKV("playlist_manifest_id", foundManifest)
	return nil
}

func (pm *PlaylistManager) CreatePlaylist(title, description string) (*youtube.Playlist, error) {
	svc := pm.yt.GetService()
	p := &youtube.Playlist{
		Snippet: &youtube.PlaylistSnippet{
			Title:       title,
			Description: description,
		},
		Status: &youtube.PlaylistStatus{
			PrivacyStatus: "unlisted",
		},
	}
	
	res, err := svc.Playlists.Insert([]string{"snippet", "status"}, p).Do()
	if err == nil {
		pm.db.LogQuotaUsage(50)
		log.Printf("🎬 Created Playlist: %s (%s)", title, res.Id)
	}
	return res, err
}

func (pm *PlaylistManager) SyncFolderToPlaylist(folderID int64) (string, error) {
	folder, err := pm.db.GetFolderByID(folderID)
	if err != nil || folder == nil {
		return "", err
	}

	if folder.PlaylistID != nil && *folder.PlaylistID != "" {
		return *folder.PlaylistID, nil
	}

	title := "NEXUS_" + folder.Name
	desc := "Nexus-Storage Folder: " + folder.Name
	if pm.db.IsStealthMode() {
		title = fmt.Sprintf("DATA_SET_%d", folderID)
		desc = "Autogenerated data collection."
	}

	p, err := pm.CreatePlaylist(title, desc)
	if err != nil {
		return "", err
	}

	_, err = pm.db.db.Exec(`UPDATE folders SET playlist_id = ? WHERE id = ?`, p.Id, folderID)
	return p.Id, err
}

func (pm *PlaylistManager) AddVideoToPlaylist(playlistID, videoID string) error {
	svc := pm.yt.GetService()
	item := &youtube.PlaylistItem{
		Snippet: &youtube.PlaylistItemSnippet{
			PlaylistId: playlistID,
			ResourceId: &youtube.ResourceId{
				Kind:    "youtube#video",
				VideoId: videoID,
			},
		},
	}
	_, err := svc.PlaylistItems.Insert([]string{"snippet"}, item).Do()
	if err == nil {
		pm.db.LogQuotaUsage(50)
		log.Printf("📎 Added Video %s to Playlist %s", videoID, playlistID)
	}
	return err
}

func (pm *PlaylistManager) DownloadLatestManifest() error {
	log.Printf("📥 Fetching manifest from Google Drive...")
	
	reader, err := pm.yt.DownloadManifestFromDrive()
	if err != nil {
		return fmt.Errorf("Drive manifest recovery failed: %w", err)
	}
	defer reader.Close()

	// 1. Download to temp file
	tempDir, _ := os.MkdirTemp("", "nexus-drive-sync-*")
	defer os.RemoveAll(tempDir)
	cloudDbPath := filepath.Join(tempDir, "cloud_manifest.db")
	
	outFile, err := os.Create(cloudDbPath)
	if err != nil {
		return err
	}
	if _, err := io.Copy(outFile, reader); err != nil {
		outFile.Close()
		return err
	}
	outFile.Close()

	// 2. Merge into DB
	log.Printf("🔄 Merging cloud records from Drive into local database...")
	if err := pm.db.MergeManifest(cloudDbPath); err != nil {
		return fmt.Errorf("DB merge failed: %w", err)
	}

	pm.db.SetKV("last_cloud_sync", time.Now().Format(time.RFC3339))
	log.Printf("✅ Cloud Manifest Sync (from Drive) completed successfully.")
	return nil
}
